import InvestmentOption from '../models/investmentOption';

export const seedInvestmentOptions = async () => {
    const count = await InvestmentOption.countDocuments();

    if (count > 0) {
        console.log('Investment options already seeded');
        return;
    }

    const options = [
        // LOW SURPLUS OPTIONS (< ₹5,000)
        {
            title: 'SIP - Small Cap Mutual Fund',
            description: 'Start investing with as little as ₹500/month in diversified mutual funds',
            type: 'SIP',
            risk: 'low',
            minAmount: 500,
            maxAmount: 2000,
            surplusTier: 'low',
            expectedReturn: '8-12% annually',
            liquidity: 'medium',
            category: 'Mutual Funds',
        },
        {
            title: 'Recurring Deposit (RD)',
            description: 'Safe monthly savings with guaranteed returns from banks',
            type: 'RD',
            risk: 'low',
            minAmount: 1000,
            maxAmount: 3000,
            surplusTier: 'low',
            expectedReturn: '5-7% annually',
            liquidity: 'low',
            category: 'Bank Deposits',
        },
        {
            title: 'Gold SIP',
            description: 'Invest in digital gold starting from ₹500',
            type: 'GOLD',
            risk: 'low',
            minAmount: 500,
            maxAmount: 2000,
            surplusTier: 'low',
            expectedReturn: '6-10% annually',
            liquidity: 'high',
            category: 'Precious Metals',
        },
        {
            title: 'Government Treasury Bills',
            description: 'Ultra-safe government-backed short-term securities',
            type: 'GOVT_BOND',
            risk: 'low',
            minAmount: 1000,
            maxAmount: 5000,
            surplusTier: 'low',
            expectedReturn: '6-7% annually',
            liquidity: 'medium',
            category: 'Government Securities',
        },

        // MEDIUM SURPLUS OPTIONS (₹5,000 - ₹15,000)
        {
            title: 'Nifty 50 Index Fund',
            description: 'Track India\'s top 50 companies with low-cost index investing',
            type: 'ETF',
            risk: 'medium',
            minAmount: 2000,
            maxAmount: 8000,
            surplusTier: 'medium',
            expectedReturn: '10-15% annually',
            liquidity: 'high',
            category: 'Index Funds',
        },
        {
            title: 'Hybrid Mutual Fund',
            description: 'Balanced mix of equity and debt for moderate growth',
            type: 'SIP',
            risk: 'medium',
            minAmount: 2000,
            maxAmount: 7000,
            surplusTier: 'medium',
            expectedReturn: '9-13% annually',
            liquidity: 'medium',
            category: 'Mutual Funds',
        },
        {
            title: 'Fixed Deposit (FD)',
            description: 'Lock-in your savings for guaranteed returns',
            type: 'FD',
            risk: 'low',
            minAmount: 5000,
            maxAmount: 15000,
            surplusTier: 'medium',
            expectedReturn: '6-8% annually',
            liquidity: 'low',
            category: 'Bank Deposits',
        },
        {
            title: 'Gold ETF',
            description: 'Trade gold like stocks on the exchange',
            type: 'GOLD',
            risk: 'medium',
            minAmount: 2000,
            maxAmount: 6000,
            surplusTier: 'medium',
            expectedReturn: '7-11% annually',
            liquidity: 'high',
            category: 'Precious Metals',
        },
        {
            title: 'Blue Chip Stocks',
            description: 'Invest in established, reliable large-cap companies',
            type: 'STOCK',
            risk: 'medium',
            minAmount: 3000,
            maxAmount: 10000,
            surplusTier: 'medium',
            expectedReturn: '12-18% annually',
            liquidity: 'high',
            category: 'Stocks',
        },

        // HIGH SURPLUS OPTIONS (₹15,000+)
        {
            title: 'Equity Mutual Fund SIP',
            description: 'High-growth potential with diversified equity portfolio',
            type: 'SIP',
            risk: 'high',
            minAmount: 5000,
            maxAmount: 20000,
            surplusTier: 'high',
            expectedReturn: '12-20% annually',
            liquidity: 'medium',
            category: 'Mutual Funds',
        },
        {
            title: 'S&P 500 Index Fund',
            description: 'Invest in top 500 US companies for global diversification',
            type: 'ETF',
            risk: 'medium',
            minAmount: 3000,
            maxAmount: 15000,
            surplusTier: 'high',
            expectedReturn: '10-16% annually',
            liquidity: 'high',
            category: 'International Funds',
        },
        {
            title: 'US Fractional Stocks',
            description: 'Own fractions of expensive US stocks like Apple, Google',
            type: 'STOCK',
            risk: 'high',
            minAmount: 2000,
            maxAmount: 10000,
            surplusTier: 'high',
            expectedReturn: '15-25% annually',
            liquidity: 'high',
            category: 'International Stocks',
        },
        {
            title: 'Cryptocurrency (Bitcoin/Ethereum)',
            description: 'High-risk, high-reward digital currency investment',
            type: 'CRYPTO',
            risk: 'high',
            minAmount: 1000,
            maxAmount: 5000,
            surplusTier: 'high',
            expectedReturn: 'Highly volatile',
            liquidity: 'high',
            category: 'Cryptocurrency',
        },
        {
            title: 'Sector ETF (IT/Pharma)',
            description: 'Focused investment in specific high-growth sectors',
            type: 'ETF',
            risk: 'high',
            minAmount: 4000,
            maxAmount: 15000,
            surplusTier: 'high',
            expectedReturn: '14-22% annually',
            liquidity: 'high',
            category: 'Sector Funds',
        },
        {
            title: 'P2P Lending',
            description: 'Lend to individuals/businesses for higher returns',
            type: 'P2P',
            risk: 'high',
            minAmount: 5000,
            maxAmount: 20000,
            surplusTier: 'high',
            expectedReturn: '12-18% annually',
            liquidity: 'low',
            category: 'Alternative Investments',
        },
    ];

    await InvestmentOption.insertMany(options);
    console.log('✅ Investment options seeded successfully');
};
